#!/usr/bin/env bash
# KMO DEV-Stage Cloudflare Tunnel Setup [CRUX-MK]
# Erzeugt einen Named-Tunnel "kmo-dev" mit ingress-Rules fuer kmo-gateway:8080.
# Spec: branch-hub/blueprints/SPEC-KMO-DEV-STAGE-CLOUDFLARE-DOCKER-2026-04-30.md
# Idempotent -- mehrfaches Ausfuehren ist sicher.

set -euo pipefail

TUNNEL_NAME="${TUNNEL_NAME:-kmo-dev}"
CONFIG_DIR="${HOME}/.cloudflared"
CONFIG_FILE="${CONFIG_DIR}/config.yml"
HOSTNAME="${KMO_DEV_HOSTNAME:-kmo-dev.example.com}"

log() { printf '[setup-cloudflared] %s\n' "$*"; }
err() { printf '[setup-cloudflared] ERROR: %s\n' "$*" >&2; }

# 1. Pre-Check: cloudflared verfuegbar?
if ! command -v cloudflared >/dev/null 2>&1; then
  err "cloudflared nicht gefunden."
  err "Install Hint: brew install cloudflared"
  err "Oder: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"
  exit 1
fi
log "cloudflared gefunden: $(cloudflared --version 2>&1 | head -n1)"

mkdir -p "${CONFIG_DIR}"

# 2. Login (idempotent -- legt cert.pem an, falls fehlend).
if [ ! -f "${CONFIG_DIR}/cert.pem" ]; then
  log "cert.pem fehlt -- starte cloudflared tunnel login (Browser oeffnet sich)..."
  cloudflared tunnel login
else
  log "cert.pem vorhanden -- login uebersprungen."
fi

# 3. Tunnel anlegen falls nicht vorhanden.
TUNNEL_ID="$(cloudflared tunnel list 2>/dev/null | awk -v n="${TUNNEL_NAME}" '$2==n {print $1; exit}')"
if [ -z "${TUNNEL_ID}" ]; then
  log "Lege Tunnel '${TUNNEL_NAME}' an..."
  cloudflared tunnel create "${TUNNEL_NAME}"
  TUNNEL_ID="$(cloudflared tunnel list 2>/dev/null | awk -v n="${TUNNEL_NAME}" '$2==n {print $1; exit}')"
fi
if [ -z "${TUNNEL_ID}" ]; then
  err "Tunnel-ID konnte nicht ermittelt werden."
  exit 2
fi
log "Tunnel-ID: ${TUNNEL_ID}"

# 4. Config-File schreiben (ingress-Rules fuer kmo-gateway).
cat >"${CONFIG_FILE}" <<EOF
# KMO DEV-Stage Cloudflare Tunnel config [CRUX-MK]
# Auto-generated by setup-cloudflared.sh -- manuelle Edits werden ueberschrieben.
tunnel: ${TUNNEL_ID}
credentials-file: ${CONFIG_DIR}/${TUNNEL_ID}.json

ingress:
  - hostname: ${HOSTNAME}
    service: http://localhost:8080
  - service: http_status:404
EOF
log "Config geschrieben: ${CONFIG_FILE}"

# 5. Token-Hint fuer .env.
log "Token holen via: cloudflared tunnel token ${TUNNEL_NAME}"
log "Dann CLOUDFLARE_TUNNEL_TOKEN in dev-stage/.env setzen."

# 6. Smoke-Test.
log "Tunnel-Info:"
cloudflared tunnel info "${TUNNEL_NAME}" || err "tunnel info fehlgeschlagen (Tunnel evtl. nicht aktiv)"

log "Setup abgeschlossen. Naechster Schritt: docker compose -f docker-compose.kmo-dev.yml up"
